import "./globals.css";
import { Inter, Prata } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

const prata = Prata({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--font-prata",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${prata.variable}`}>{children}</body>
    </html>
  );
}
